# Generated by Django 4.1 on 2022-09-28 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create', models.DateTimeField(auto_now_add=True, verbose_name='')),
                ('by_user', models.CharField(blank=True, max_length=50, null=True, verbose_name='User')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Product name')),
                ('price', models.PositiveIntegerField(blank=True, null=True, verbose_name='Price')),
                ('discount_price', models.PositiveIntegerField(blank=True, null=True, verbose_name='Discount price')),
                ('short_description', models.CharField(blank=True, max_length=50, null=True, verbose_name='Short description')),
                ('long_description', models.TextField(blank=True, null=True, verbose_name='Long description')),
                ('quantity_in_stock', models.PositiveIntegerField(blank=True, null=True, verbose_name='Quantity')),
                ('available', models.BooleanField(blank=True, default=True, null=True, verbose_name='Available')),
                ('product_type', models.CharField(blank=True, choices=[('physic', 'Physic'), ('numeric', 'Numeric'), ('book', 'Book'), ('download_prod', 'Download Product')], max_length=50, null=True, verbose_name='Type of product')),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Image')),
            ],
        ),
    ]
