# Generated by Django 4.1 on 2022-09-29 08:40

from django.db import migrations, models
import product.utils


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(blank=True, null=True, upload_to=product.utils.upload_to, verbose_name='Image'),
        ),
    ]
