# Generated by Django 4.1 on 2022-10-08 20:41

from django.db import migrations, models
import django.db.models.deletion
import product.utils


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_product_available_alter_product_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.FileField(upload_to='', verbose_name='Product Gallery'),
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=product.utils.user_directory_path, verbose_name='Product Gallery')),
                ('product_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='Product files')),
            ],
        ),
    ]
