# Generated by Django 4.1 on 2022-10-08 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_product_product_image_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(upload_to='', verbose_name='Product Gallery'),
        ),
    ]
