# Generated by Django 4.1 on 2022-10-07 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='First name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last name')),
                ('company', models.CharField(max_length=50, verbose_name='Company name')),
                ('contry', models.CharField(max_length=50, verbose_name='Contry /  Region')),
                ('city', models.CharField(max_length=50, verbose_name='City /  Team')),
                ('address', models.CharField(max_length=50, verbose_name='Street address')),
                ('postal_code', models.CharField(max_length=50, verbose_name='Postal code / ZIP')),
                ('phone', models.CharField(max_length=254, verbose_name='Phone number')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Order notes (optional)')),
            ],
        ),
    ]
