# Generated by Django 4.1 on 2022-09-29 08:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0002_alter_product_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create', models.DateTimeField(auto_now_add=True, verbose_name='Cart created at')),
                ('update', models.DateTimeField(auto_now=True, verbose_name='cart updated at')),
                ('cart_state', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('cancel', 'Cancel')], max_length=50, verbose_name='Cart state')),
                ('transaction_id', models.CharField(max_length=100, verbose_name='Transaction id')),
                ('complete', models.BooleanField(default=False, verbose_name='Complete cart')),
                ('cart_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Cart user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create', models.DateTimeField(auto_now_add=True, verbose_name='Cart created at')),
                ('update', models.DateTimeField(auto_now=True, verbose_name='cart updated at')),
                ('product_quantity', models.PositiveIntegerField(verbose_name='Cart item product')),
                ('cart_item_state', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('cancel', 'Cancel')], max_length=50, verbose_name='Product state')),
                ('cart_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.cart', verbose_name='Relate cart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='Cart product')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
