# Generated by Django 4.1 on 2022-10-06 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_state',
            field=models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('cancel', 'Cancel')], default='Pending', max_length=50, verbose_name='Cart state'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='product_quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Cart item product'),
        ),
    ]
